### PR TITLE
Bug fixed when style is switched from DEFAULT to OTHER

### PR DESCRIPTION
**Pull request by abusaeed2433**
After using android_default, It can't be changed to other style. It keeps using the android_default style since instance of CreateDialog was not null while showing other style. This is fixed here.

### CODE REVIEW

**Comment by saadahmedscse** [comment]
Have you checked it properly?

**Comment by abusaeed2433** [comment]
Yes. You can also check it.
Add two button

1.  button1 for showing default popup,
2.  button2 for showing success popup

Now click button1, it will show default popup. Then click button2, it will still show default popup, but with different title and heading that you passed in onClick of button2

**Comment by saadahmedscse** [comment]
Ok, I'll check it out.

**Comment by saadahmedscse** [comment]
Yeah, I got your point.. Thank you.

**Comment by saadahmedscse** [comment]
You should commit individual file with exact commit message, not all together.

**Comment by abusaeed2433** [comment]
Actually I was testing all the popup by adding buttons and was in hurry.

**Pull request merged**
